### ISSUE TITLE
libaxolotl-javascript vs axolotl-crypto-curve25519

### ISSUE THREAD

**Issue by tvandergeer** [joebandenburg/libaxolotl-crypto-node#1]
Amazing work what you've done here! I'm currently doing some research on the possibility to add end-to-end encryption to our node-whatsapi project. It looks like we can directly profit from your work on the axolotl implementation for javascript and node.

Just one thing that I was wondering when looking through your code; in the readme of libaxolotl-crypto-node you're referring to libaxolotl-javascript but in the package.json it only includes axolotl-crypto-curve25519 as dependency. Is axolotl-crypto-curve25519 superseding libaxolotl-javascript?

**Comment by tvandergeer** [comment]
Ok, never mind... I found out I need them both.

**Comment by joebandenburg** [comment]
Hi Tom. Sorry I didn't get back to you sooner. Thanks for taking an interest in my code.

I'm glad you've resolved the issue. You need `libaxolotl-javascript` and, optionally, `libaxolotl-crypto-node`. `libaxolotl-crypto-node` depends on `libaxolotl-crypto-curve25519`. I've used the names of the GitHub repositories here. The package names in NPM are a little different, but you can see that from looking at the `package.json` files in the respective repositories.
